set eprj_proj_name "art7sb_e2bus"
set eprj_def_root "../src/art7sb.eprj"
set eprj_top_entity "a7sb_e2bus"
set eprj_board_part ""
set eprj_board_files_path ""
set eprj_part "xc7a35tftg256-1"
set eprj_target_language "VHDL"
set eprj_simulator_language "Mixed"
set eprj_default_lib "work"
set eprj_synth_flow "Vivado Synthesis 2019"
set eprj_synth_strategy "Flow_PerfOptimized_high"
set eprj_impl_flow "Vivado Implementation 2019"
set eprj_impl_strategy "Performance_Retiming"
set eprj_vivado_version "2019.1.1"
set eprj_vivado_version_allow_upgrade true
