set_property IOSTANDARD LVCMOS33 [get_ports ref_clk]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports phy2rmii_crs_dv]
set_property IOSTANDARD LVCMOS33 [get_ports {phy2rmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {phy2rmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports rmii2phy_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii2phy_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii2phy_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports ext_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports phy_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports phy_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]
set_property PACKAGE_PIN D4 [get_ports ref_clk]
set_property PACKAGE_PIN C3 [get_ports phy_rst_n]
set_property PACKAGE_PIN G5 [get_ports {phy2rmii_rxd[1]}]
set_property PACKAGE_PIN C7 [get_ports {phy2rmii_rxd[0]}]
set_property PACKAGE_PIN B4 [get_ports {rmii2phy_txd[1]}]
set_property PACKAGE_PIN D6 [get_ports {rmii2phy_txd[0]}]
set_property PACKAGE_PIN E6 [get_ports phy2rmii_crs_dv]
set_property PACKAGE_PIN A5 [get_ports rmii2phy_tx_en]
set_property PACKAGE_PIN A8 [get_ports ext_rst_n]
set_property PACKAGE_PIN C8 [get_ports led1]
set_property PACKAGE_PIN B7 [get_ports phy_mdc]
set_property PACKAGE_PIN B6 [get_ports phy_mdio]
set_property PACKAGE_PIN N13 [get_ports i2c_sda]
set_property PACKAGE_PIN N16 [get_ports i2c_scl]
set_property PULLUP true [get_ports phy_mdio]
set_property PULLUP true [get_ports phy_mdc]
set_property PULLUP true [get_ports i2c_sda]
set_property PULLUP true [get_ports i2c_scl]

set_property DRIVE 8 [get_ports phy_mdc]
set_property DRIVE 8 [get_ports phy_mdio]
set_property DRIVE 8 [get_ports led1]
set_property DRIVE 8 [get_ports phy_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN N11 [get_ports sys_clk]


